import { Link } from 'react-router-dom';
import StudentLayout from '../../components/StudentLayout';

export default function StudentReports() {
  return (
    <StudentLayout searchPlaceholder="Search records...">
      <div className="mb-6">
        <h1 className="text-3xl font-black tracking-tight text-slate-900">Reports</h1>
        <p className="mt-1 text-sm text-slate-500">Academic report card information.</p>
      </div>

      {/* Main notice card */}
      <div className="rounded-2xl border border-slate-200 bg-white p-8 shadow-sm">
        <div className="flex flex-col items-center text-center">
          {/* Icon */}
          <div className="flex h-20 w-20 items-center justify-center rounded-full bg-slate-100">
            <svg className="h-10 w-10 text-slate-500" viewBox="0 0 24 24" fill="currentColor" aria-hidden="true">
              <path d="M14 2H6a2 2 0 0 0-2 2v16a2 2 0 0 0 2 2h12a2 2 0 0 0 2-2V8l-6-6zm-1 1.5L18.5 9H13V3.5zM6 20V4h5v7h7v9H6z" />
            </svg>
          </div>

          <h2 className="mt-5 text-2xl font-black text-slate-900">
            Report Cards Are Distributed In Person
          </h2>

          <p className="mt-3 max-w-lg text-sm leading-relaxed text-slate-500">
            Official report cards are generated by the school and printed for distribution. 
            They are <span className="font-semibold text-slate-700">not available digitally</span> through 
            this portal. You are required to visit the school to collect your printed report card.
          </p>

          {/* Divider */}
          <div className="my-8 w-full border-t border-slate-100" />

          {/* Two-column info boxes */}
          <div className="grid w-full gap-4 sm:grid-cols-2">
            <div className="rounded-xl border border-slate-100 bg-slate-50 p-5 text-left">
              <div className="mb-2 flex items-center gap-2">
                <svg className="h-5 w-5 shrink-0 text-emerald-500" viewBox="0 0 24 24" fill="currentColor" aria-hidden="true">
                  <path d="M12 2a10 10 0 1 0 0 20A10 10 0 0 0 12 2zm-1 14.4-3.7-3.7 1.4-1.4 2.3 2.3 4.8-4.8 1.4 1.4L11 16.4z" />
                </svg>
                <span className="text-sm font-bold text-slate-900">Track Performance by Subject</span>
              </div>
              <p className="text-xs leading-relaxed text-slate-500">
                You can monitor your academic performance subject by subject from the Academics page at any time.
              </p>
              <Link
                to="/student/academics"
                className="mt-4 inline-flex items-center gap-1.5 rounded-lg bg-slate-900 px-4 py-2 text-xs font-bold text-white transition hover:bg-slate-700"
              >
                Go to Academics
                <svg className="h-3.5 w-3.5" viewBox="0 0 24 24" fill="currentColor" aria-hidden="true">
                  <path d="M10 17l5-5-5-5v10z" />
                </svg>
              </Link>
            </div>

            <div className="rounded-xl border border-slate-100 bg-slate-50 p-5 text-left">
              <div className="mb-2 flex items-center gap-2">
                <svg className="h-5 w-5 shrink-0 text-blue-500" viewBox="0 0 24 24" fill="currentColor" aria-hidden="true">
                  <path d="M12 2C8.13 2 5 5.13 5 9c0 5.25 7 13 7 13s7-7.75 7-13c0-3.87-3.13-7-7-7zm0 9.5a2.5 2.5 0 1 1 0-5 2.5 2.5 0 0 1 0 5z" />
                </svg>
                <span className="text-sm font-bold text-slate-900">Collect Your Report Card</span>
              </div>
              <p className="text-xs leading-relaxed text-slate-500">
                Visit the school administration office during working hours to receive your official printed report card.
              </p>
            </div>
          </div>
        </div>
      </div>
    </StudentLayout>
  );
}
